services:
  # 1. TRẠM TRUNG CHUYỂN TIN NHẮN
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ketibmall_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  # 2. DATABASE CHO WEB TMĐT (Khối 1)
  db_app:
    image: postgres:15-alpine
    container_name: ketibmall_db_app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${APP_DB_NAME}

  # 3. DATABASE CHO HỆ THỐNG KHO (Khối 2)
  db_inventory:
    image: postgres:15-alpine
    container_name: ketibmall_db_inventory
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${INVENTORY_DB_NAME}