events {
    worker_connections 1024;
}

http {
    # Bắt buộc phải có dòng này để Nginx load đúng CSS, JS và Hình ảnh
    include       mime.types;
    default_type  application/octet-stream;
    
    # Cho phép upload file ảnh lớn (tối đa 50MB)
    client_max_body_size 50M; 

    # Trỏ đúng vào tên service trong docker-compose của bạn
    upstream app_service {
        server app_api:8000;
    }

    upstream inventory_service {
        server inventory_api:8001;
    }

    server {
        listen 8080;

        # 1. PHỤC VỤ GIAO DIỆN WEB (FRONTEND)
        location / {
            root /usr/share/nginx/html;
            index login.html; # Mặc định khách vào sẽ đẩy ra trang Đăng nhập
            try_files $uri $uri/ /login.html;
        }

        # 2. Chuyển hướng các request API Kho
        location /api/inventory/ {
            proxy_pass http://inventory_service/api/inventory/;
        }

        # 3. Chuyển hướng các request API Bán hàng
        location /api/ {
            proxy_pass http://app_service/api/;
        }

        # 4. Chuyển hướng để load ảnh sản phẩm từ Backend
        location /static/ {
            proxy_pass http://app_service/static/;
        }

        # 5. Mở đường cho tài liệu Swagger UI của App
        location /docs {
            proxy_pass http://app_service/docs;
        }
        
        # 6. Mở đường cho file cấu trúc API (Swagger cần file này để vẽ giao diện)
        location /openapi.json {
            proxy_pass http://app_service/openapi.json;
        }
    }
}